### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#1]
Produce a rough diagram to allow the planned architecture to be considered.

Ian will provide write access to this empty diagram:
https://docs.google.com/drawings/d/1MbwKyFs3XFS8df1DkVZ2Rh6JPPLowOqjisYQq02n2iI/edit

Plan to include:
* front-end
* middleware
* databaes
* data flows & technologies used

**Comment by IanMayo** [comment]
Ok, I've impatiently had a go at the system architecture myself.   The components are there, we just need to select/name the technologies.

**Comment by krsnik93** [comment]
Is Bootstrap for css already set in stone or do we have some flexibility there? Having React and possibly Material UI (depending on your taste) would be interesting.

**Comment by IanMayo** [comment]
Bootstrap isn't set in stone.  Material would be fine.

For the current complexity I don't think React is justified - since it introduces the "transpile" step to the deployment. If (for now) we stick with pure JS the raw code just gets deployed & works.

**Comment by robintw** [comment]
I've had a brief look at the architecture diagram and everything looks good. One (minor) comment: I'm not sure we'll necessarily need `flask-restx` at this point - I think that mostly becomes useful when you're doing a 'full' REST API with `GET` and `PUT` and all sorts of other HTTP methods. For providing a simple JSON when you hit a certain URL, I think we could probably just use a plain Flask route.

**Comment by IanMayo** [comment]
Thanks @robintw  - good point.

We're _expecting_ the data to come from one SQL call.  So, you're right - we don't need full REST if there is only one end-point.  Our implementation isn't very different from the simple example:
![image](https://user-images.githubusercontent.com/1108513/114369236-14107080-9b76-11eb-9934-37da8fbdaa08.png)

Have updated design to remove RestX add-in, since we only require one end-point.

**Comment by IanMayo** [comment]
@krsnik93  - are you happy with dropping RESTX?

**Comment by IanMayo** [comment]
Done. Architecture now mature.
