### ISSUE TITLE
Reflect new flag for `includeInTimeline`

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#11]
This core Pepys issue requires `pepys-timeline` updates:
https://github.com/debrief/pepys-import/issues/854

**Comment by krsnik93** [comment]
added here: https://github.com/debrief/pepys-timeline/commit/2b16a7b7bb3a3b66ace0a5ba5fccca213b26b104

**Comment by IanMayo** [comment]
Resolved.
