### ISSUE TITLE
Create more rows for dummy data

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#12]
Our mock data currently just shows 3 participants for each serial.

It would be useful to have timelines showing different numbers of participants.  It's fine to copy/paste data, though it would be _nice_ if the names got some quick letter changes to keep them unique.

I suggest these numbers of participants:  3, 8, 6, 24, 4

(the analysts _think_ 24 will be the largest number of participants).

**Comment by krsnik93** [comment]
@IanMayo added. I repeated existing data. Please let know if you want unique values.

**Comment by IanMayo** [comment]
One change, please @krsnik93  - could you limit it to 5 serial please?

I'm leaving >5 serials for a future requirement. The analysts were quite clear they were only going to analyse up to 5 serials a day.

**Comment by krsnik93** [comment]
@IanMayo I added sixth serial into `.json` just to see that if the flag is false, it won't get generated. 

Do you want me to, on frontend, fetch `.json`, render up to 5, discard the rest?

**Comment by krsnik93** [comment]
I think the best way would be to have `LIMIT` in the query, once we reach that phase and go past the mock `.json` file.

**Comment by IanMayo** [comment]
> @IanMayo I added sixth serial into `.json` just to see that if the flag is false, it won't get generated.

I see 6 serials here: https://pepys-timeli-ui-prototy-focdox.herokuapp.com/

**Comment by krsnik93** [comment]
this is what I see:
![image](https://user-images.githubusercontent.com/13034472/115898246-3dbe7700-a455-11eb-9d56-bd09d17840a3.png)

**Comment by IanMayo** [comment]
Strange I see one lower down, too:
![image](https://user-images.githubusercontent.com/1108513/115898643-b291b100-a455-11eb-8f82-68f5cfbceabf.png)

The console shows 6 charts being processed (the first one has a duplicated name)
![image](https://user-images.githubusercontent.com/1108513/115898703-c2a99080-a455-11eb-8530-cbad3f753e85.png)

**Comment by krsnik93** [comment]
logs should look like this:
![image](https://user-images.githubusercontent.com/13034472/115899149-51b6a880-a456-11eb-87d8-ec608eac97c4.png)

**Comment by krsnik93** [comment]
Sounds like frontend got cached in the browser in some way. Maybe CTRL + F5 would help...

**Comment by IanMayo** [comment]
> Sounds like frontend got cached in the browser in some way. Maybe CTRL + F5 would help...

Aah, you're completely right :-D

**Comment by IanMayo** [comment]
Done.
