### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#13]
The timelines all _currently_ have the same number of participants, so they're of equal size.

An issue (#12) has been created to create different numbers of participants, to generate different sized timelines.

Once that is complete, it would be great if the layout could dynamically flow to _pack_ the timelines into the smallest area.  So, one with 24 participants may occupy the whole of a right-hand column, but several with a small number would be put on top of each other in the left-hand column.

I tried looking for a lib to handle this, but couldn't find one.  @tanganellilore may have better look searching.  Oops, found one 5 minutes later: https://masonry.desandro.com/

[Here](https://stackoverflow.com/a/57922519/92441) is a demo I found.

**Comment by IanMayo** [comment]
@krsnik93 - I've invited @tanganellilore to develop this based on his previous `index.html` work, to avoid him having to spin up Python infrastructure.  Once he has a working demonstrator, I'll invite you to re-apply his changes to `index.html` in your branch.  Is that ok with you?

**Comment by krsnik93** [comment]
@IanMayo Yes, fine with me. Thanks.

**Comment by IanMayo** [comment]
Hello @tanganellilore -  I see that @krsnik93  has created some more dummy data.  You may wish to copy it:
https://github.com/debrief/pepys-timeline/pull/6/commits/8fcdc1b85400bffec7a4a066e32abdec11303c66#diff-12aca30fc610d3516df3724870a344119fcf9fef50bbeb733157fade00c4e661

**Comment by tanganellilore** [comment]
@IanMayo and team.
I tired to implement Masonry (or library similar) and I'm able to manage bootsrap with these library.
The problem, for my point of view, that the layout will not the layout that you expected.
See picture below:

![image](https://user-images.githubusercontent.com/35271287/116037630-ac275300-a668-11eb-956b-ac48f4ca8355.png)

**Comment by IanMayo** [comment]
Thanks for the @tanganellilore - sometimes it's only possible to know what something will look like once it's implemented.

I'll share your screenshot with the analysts.

I did imagine that the masonry layout would allow some components to expand to fill the space available.  But, I now think that the different sizes/scales may make it slightly more difficult to interpret.

Actually, @tanganellilore - could you push the above version to a new branch, and create a Draft Pull Request?  Then I can give the analysts a "live mockup".

**Comment by tanganellilore** [comment]
added new branch `UI_test_masonry` based on UI_prototype branch.

moreover added `UI_timedate_test` that have also time on the top of the graph

**Comment by IanMayo** [comment]
We have a _playable_ version of the layout here:
https://pepys-timeli-ui-test-ma-wvbzev.herokuapp.com/

But, now that I'm able to play with it, I'm not convinced it brings any benefits.  We aren't able to usefully display an extra information.  If there were more than 5 serials, it may allow us to display 8 or 10, but analysts will only look at a max of 5 per day.

Aah, hold on. There could be a benefit.  What if we switched to a 4 column layout with masonry.  That would make the timelines (slightly) larger, and easier to read.

**Comment by tanganellilore** [comment]
yes, advantage with masonry if if you have a lot of div with different height and multiple device.

**Comment by IanMayo** [comment]
Done.
