### ISSUE TITLE
Timelines require time scale

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#14]
The timelines will be more informative if they showed the times at the top of the x axis, like the `visavail` demo for dates & times:
https://flrs.github.io/visavail/docs/samples/dates_and_times.html

**Comment by tanganellilore** [comment]
@IanMayo: deployed on branch : UI_timedate_test

This branch have masonry + time on header of graph

**Comment by IanMayo** [comment]
Fixed. Implemented in #6
