### ISSUE TITLE
Possible issue with timeline stats

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#18]
We're now have some states in the time periods for the `Jolly Warrior 21/01`.

We have data for the platform `DOFF`, which is a `Warship` type that takes part in serials `J05056` and `J05250`.

The data is in one minute time steps, and the `PlatformType`.`default_data_interval` for a warship is 30 seconds. So, if our _test_ is 5 times the default value, we should have continuous coverage.

However, it appears the database code is treating every step as gap.
![image](https://user-images.githubusercontent.com/1108513/116439284-4a710f80-a847-11eb-9acb-d5c9881ad2f6.png)

Aah, we should now have a non-zero %age coverage for `SPLENDID` and `DOFF`.

Could you investigate this further please @arunlal-v

**Comment by krsnik93** [comment]
@IanMayo I might have set up the coverage formula wrong. Do both "C" and "G" periods add up into coverage? Coverage is only missing if no observation at all (neither one of the above)?

**Comment by krsnik93** [comment]
![image](https://user-images.githubusercontent.com/13034472/116454679-2833bd80-a858-11eb-9451-7b2bc78670ea.png)

Looks healthier except for overlapping issues.

**Comment by krsnik93** [comment]
![image](https://user-images.githubusercontent.com/13034472/116455731-5796fa00-a859-11eb-8130-01143c118ae2.png)

![image](https://user-images.githubusercontent.com/13034472/116455915-87de9880-a859-11eb-88da-e4919226dc5b.png)

**Comment by IanMayo** [comment]
Not quite @krsnik93  :-)

The current grey bars we see represent the period that the Participant was in the Serial.  For most of them, it's the whole period - but we that SALT was only present for part of both.

So, these periods are the `denominator` for the percentage.

The `numerator` is the sum of the `C` (coverage) periods.

So, at top left we see DOFF was in the serial for the full 30 minutes.   I _think_ we're getting coverage for DOFF.  So, we add up the `C` periods.  I _think_ the Coverage & Gaps is currently broken.  So, let's imagine it was present for the first 10 minutes and the last 10 minutes.  So, the percentage is (10 + 10) / 30 = 66%.

If we haven't received any coverages, the numerators will be zero, thus 0%.

The above _could_ be calculated in PostGres.  But, it's my preference for it to be calculated in Python/Flask - since that's where we'll (eventually) aim for high test code coverage - and we'll keep PostGres & JavaScript as _thin_ as we can.

**Comment by krsnik93** [comment]
@IanMayo a lot of the periods have the same start and end time:
![image](https://user-images.githubusercontent.com/13034472/116458582-ba3dc500-a85c-11eb-89a0-d7f8e807071c.png)

EDIT: actually all of the C type periods seem to have the same start and end times. This is why it comes out as 0%

**Comment by krsnik93** [comment]
Also the first 2 stats (one C, one G) for a participant seem to cover the whole period. This might throw off the averages. I don't know if we need this at all. I think you still want to show 3 states (C, G, and simply unobserved)?

**Comment by krsnik93** [comment]
![image](https://user-images.githubusercontent.com/13034472/116588610-aacd8300-a913-11eb-9580-8a3f6ae6575e.png)

@IanMayo Does this look correct re SALT?

**Comment by IanMayo** [comment]
The big test is CRAY at top-left.  It's 30 minutes long, and has 20 mins of coverage: that's 66.6%.

For SALT, we don't have any coverage - so it is 0%.

It is only present for part of each serial - so the limited grey bar is correct.

**Comment by IanMayo** [comment]
Note: @krsnik93  - could we just display integer percentages please?  Decimal places don't have value in this context. That will probably let the figures fit fully within the right-hand whitespace.
