### ISSUE TITLE
Use QuadGraph rather than Platform Name in Timeline queries

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#19]
Our neat layout relies on platforms having a 4-character label:
![image](https://user-images.githubusercontent.com/1108513/116439958-f9ade680-a847-11eb-8434-b95387ade96c.png)

This comes from the QuadGraph field, though I see we _happen_ to be using platforms that have a 4-digit full name.

So, in the database query we need to move from PlatformName to Quadgraph.

**Comment by rnllv** [comment]
The following platforms don't have Quadgraph or Trigraph information. Should the query return name for such cases?

Platform Type| Platform 
-|-
 Naval - patrol  | NARV
 Naval - frigate | ADRI
 Naval - frigate | JEAN
 Tug             | SPAR

**Comment by IanMayo** [comment]
Yes, the query should return the name, trimmed to 4 chars.  But, separate to that I'll go in and insert trigraph/quadgraph entries for them.

**Comment by IanMayo** [comment]
Oh no, @arunlal-v - I've just seen how poor the TriGraphs & Quadgraphs are:
![image](https://user-images.githubusercontent.com/1108513/116575081-3c35f880-a906-11eb-8339-90bb5843735c.png)

Are you able to do some SQL tricker to update the TriGraph & QuadGraphs to use the first 4 chars of the name (if unique), else three chars plus an integer counter?

**Comment by rnllv** [comment]
Yep, let me check.

**Comment by rnllv** [comment]
Please check now, @IanMayo

**Comment by IanMayo** [comment]
Yes, great.
