### ISSUE TITLE
Updates for new visavail

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#7]
`visavail` has been updated, and includes two new features to meet our requirements,

We should update the local copy, and update `index.html` to use the new formatting.

**Comment by tanganellilore** [comment]
Good afternoon @IanMayo,

as requested you can find new release for frontend under branch `lorenzo_dev` .
I adjust some style to make more "modern"  with usage of bootsrap and bootstrap material.

Below what was changed:

- [x] Use best practice structure of project (folder and so on)
- [x] Align new features of visavail
- [x] Generate graph in dynamic way
- [x] Rework of function that parsed data provided by db
- [x] Externalise all libraries where is not necessary
- [x] Customize bootstrap to 10 columns

**Comment by IanMayo** [comment]
Thanks.

We do have a "special" requirement for this project. The target network won't have an Internet connection.
So we need all the dependencies to be present in the repo.
Would you mind updating the branch to include your chosen versions of the dependencies please?

**Comment by tanganellilore** [comment]
Sorry, I missed this point, i will update everything Tomorrow morning.

**Comment by tanganellilore** [comment]
Done.
One more point that i missed.
I removed all function related resize of graph, due to the fact visavail have the functionality to resize itself

**Comment by IanMayo** [comment]
Implemented.
